# Generated by Django 2.2.12 on 2021-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('special', models.IntegerField()),
                ('right_answer', models.IntegerField(default=0)),
            ],
        ),
    ]
