# Generated by Django 2.2.12 on 2021-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketazaku', '0002_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AddField(
            model_name='answers',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
