# Generated by Django 2.2.12 on 2021-12-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketazaku', '0003_auto_20211215_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='anketazaku.Answers'),
        ),
    ]
