# Generated by Django 2.2.12 on 2021-12-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketazaku', '0004_auto_20211217_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='special',
        ),
    ]
