# Generated by Django 2.2.12 on 2021-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketazaku', '0005_auto_20211217_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rightanswer',
            field=models.IntegerField(default=0),
        ),
    ]
