# Generated by Django 3.2.9 on 2021-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketazaku', '0007_auto_20211217_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rightone',
            field=models.CharField(choices=[('a', 'a'), ('an', 'an')], max_length=2),
        ),
    ]
